<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class Module08Seeder extends Seeder
{
    public function run(): void
    {
        // Limpar questões antigas do bloco 8 antes de inserir as novas
        Question::where('block', 8)->delete();

        $textSUS = "O Sistema Único de Saúde (SUS) foi criado em 1988, após décadas de pressões e debates de movimentos sociais e profissionais de saúde em favor de um sistema público para todos os brasileiros. Essa foi uma grande conquista porque até essa data o atendimento nos serviços públicos de saúde era restrito a determinados programas – como vacinação, tratamento de doenças transmissíveis – ou a determinadas parcelas da população – como trabalhadores com carteira assinada e seus dependentes. São raros os países nos quais a lei estabelece que o sistema público seja responsável pelo atendimento integral da população, desde a prevenção de doenças até o final do tratamento, incluindo o fornecimento gratuito de medicamentos.\n\nAté 1988 a saúde não era considerada um direito de todos. Quem tinha carteira de trabalho assinada e pagava a Previdência Social tinha direito ao atendimento nos serviços públicos. A população que não podia pagar por atendimento particular e não “tinha INPS” era chamada de indigente ou carente. Parece incrível, mas somente com a promulgação da nova Constituição Federal, chamada de “Constituição Cidadã”, a lei brasileira passou a definir que “a saúde é um direito de todos e um dever do Estado.”\n\nDe 1988 para cá, pouco a pouco, o Sistema Único de Saúde começou a se transformar em realidade, embora ainda precise avançar muito para funcionar como está definido na lei. Os municípios, por exemplo, também passaram a ser responsáveis pelo sistema. Alguns deles avançaram mais, outros menos, de acordo com o compromisso dos governantes em transformar a lei em medidas práticas.\n\nExistem, por exemplo, municípios brasileiros que já contam com equipes do Programa de Saúde da Família para atender 100% da população. Outros estão apenas começando. Em muitos deles, a população passou a ter voz ativa nas Conferências de Saúde, realizadas a cada quatro anos, em todo o país, assim como no Conselho Municipal de Saúde, no qual os usuários dos serviços têm direito à metade das vagas. Os conselhos podem controlar, cada vez mais, o uso dos recursos públicos depositados no Fundo Municipal de Saúde.\n\nOs problemas mais graves ainda acontecem nos lugares onde os governantes não empregam corretamente os recursos depositados no Fundo de Saúde. Ou, pior ainda, tentam voltar às práticas anteriores à criação do SUS, entregando os serviços de saúde para a iniciativa privada. Mas isso não diminui o dever do Estado e dos cidadãos de defender o sistema público. Onde o SUS funciona, seus usuários sabem o que têm a defender. Onde não funciona, é preciso melhorá-lo, pois é um direito de todos os brasileiros.\n\nA lei do SUS garante o atendimento igualitário e universal (a todos os brasileiros), sem distinção de sexo, cor, etnia, renda ou classe social. Esse atendimento no sistema público é gratuito porque já foi pago pelo cidadão por meio de contribuições sociais e impostos.";

        $questions = [
            // --- PORTUGUÊS (1-20) ---
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'O texto acima visa a:',
                'options' => ['esclarecer as dificuldades do SUS', 'informar sobre a criação e origem do SUS', 'demonstrar a necessidade de sistema privado', 'mostrar a boa vontade de prefeitos'],
                'correct_answer' => 1,
                'rationale' => 'O texto tem caráter jornalístico/informativo, explicando o contexto histórico de 1988 e como o sistema se estruturou.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'De acordo com o texto, a criação do SUS se deu:',
                'options' => ['neste século', 'no século passado', 'antes da Constituição Federal', 'há precisamente três décadas'],
                'correct_answer' => 1,
                'rationale' => 'Foi criado em 1988, que pertence ao século XX (século passado).',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'A gratuidade do SUS se explica:',
                'options' => ['pela verba própria federal', 'pelo pagamento dos governos', 'pelos impostos e contribuições do cidadão', 'pelo desconto do INPS do trabalhador'],
                'correct_answer' => 2,
                'rationale' => 'O texto afirma explicitamente na última linha: "é gratuito porque já foi pago pelo cidadão por meio de contribuições sociais e impostos".',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'A criação do SUS foi consequência de:',
                'options' => ['concessão de parlamentares', 'pressão popular pela universalização', 'determinação de deputados abnegados', 'esforço da população das periferias'],
                'correct_answer' => 1,
                'rationale' => 'O texto cita "décadas de pressões e debates de movimentos sociais... em favor de um sistema público para todos".',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Acerca do acesso à saúde, o texto NÃO diz que:',
                'options' => ['o sistema particular é um direito igual', 'privados deveriam substituir o público', 'antes de 88 era restrito ao trabalhador formal', 'o Conselho exerce poder sobre recursos'],
                'correct_answer' => 1,
                'rationale' => 'O texto critica as tentativas de entregar o sistema para a iniciativa privada, defendendo o fortalecimento do sistema público.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'No trecho "Alguns deles avançaram mais... compromisso dos governantes", o termo destacados NÃO se refere a:',
                'options' => ['parlamentares', 'administradores', 'governadores', 'prefeitos'],
                'correct_answer' => 0,
                'rationale' => 'Governante, no contexto administrativo de execução da lei em municípios e estados, refere-se ao Poder Executivo (prefeitos, governadores, administradores). Parlamentares são do Legislativo.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale a opção em que a palavra destacados é um adjetivo:',
                'options' => ['décadas de pressões', 'medidas práticas', 'brasileiros (subst.)', 'recursos públicos (subst.)'],
                'correct_answer' => 1,
                'rationale' => '"Práticas" está caracterizando o substantivo "medidas".',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale a opção em que a oração está na voz passiva:',
                'options' => ['atendimento era restrito', 'A saúde não era considerada um direito', 'uso privado é um direito', 'atendimento é gratuito'],
                'correct_answer' => 1,
                'rationale' => '"Não era considerada" apresenta o verbo auxiliar ser + particípio, indicando ação sofrida pelo sujeito (saúde).',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale a opção em que é possível a presença de vírgula (adjunto deslocado):',
                'options' => ['Até 1988 a saúde não era considerada...', 'Quem tinha carteira assinada...', 'Os problemas mais graves...', 'Os municípios passaram a ser...'],
                'correct_answer' => 0,
                'rationale' => '"Até 1988" é um adjunto adverbial de tempo deslocado. A vírgula é facultativa por ser curto, mas é o lugar onde ela é gramaticalmente possível entre as opções.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'A palavra "também" no texto indica uma noção de:',
                'options' => ['exclusão', 'limite', 'inclusão', 'referência'],
                'correct_answer' => 2,
                'rationale' => '"Também" é um advérbio de inclusão.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale a opção em que o termo é um objeto direto:',
                'options' => ['tinha direito', 'atender 100% da população', 'dever do Estado', 'melhorá-lo'],
                'correct_answer' => 1,
                'rationale' => 'Quem atende, atende alguém. "100% da população" completa o sentido do verbo atender sem preposição obrigatória.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale a opção em que a expressão constitui o PREDICADO da oração:',
                'options' => ['SUS (sujeito)', 'garante o atendimento igualitário (predicado)', 'Até 1988 a saúde (adjunto+sujeito)', 'O uso de serviços privados (sujeito)'],
                'correct_answer' => 1,
                'rationale' => 'Predicado é tudo aquilo que se declara sobre o sujeito ("garante o atendimento...").',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale a opção em que o termo é o SUJEITO da oração:',
                'options' => ['Esse atendimento no sistema público', 'municípios brasileiros', 'Os conselhos', 'equipes do Programa'],
                'correct_answer' => 2,
                'rationale' => 'Quem pode controlar? Os conselhos.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale a substituição CORRETA para o termo embora:',
                'options' => ['embora (desde que)', 'de acordo com (conforme)', 'porque (mesmo que)', 'pois (portanto)'],
                'correct_answer' => 1,
                'rationale' => '"De acordo com" e "Conforme" são conjunções conformativas equivalentes.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale a opção onde todos os termos são substantivos:',
                'options' => ['conquista - data - atendimento', 'municípios - sistema', 'décadas - pressões - debates', 'conselhos - uso - recursos'],
                'correct_answer' => 2,
                'rationale' => 'Décadas, pressões e debates são nomes (substantivos) de conceitos e períodos.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale a forma verbal que NÃO está no infinitivo:',
                'options' => ['pagar', 'melhorá-lo', 'está', 'defender'],
                'correct_answer' => 2,
                'rationale' => '"Está" é verbo estar conjugado na 3ª pessoa do singular do presente do indicativo. Os outros terminam em -r.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Não indica circunstância de tempo em:',
                'options' => ['até essa data', 'pouco a pouco', 'apenas começando', 'a cada quatro anos'],
                'correct_answer' => 2,
                'rationale' => '"Apenas começando" indica um estado/ação em curso, não um marcador temporal específico como os outros.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Assinale o pronome indefinido:',
                'options' => ['Essa', 'isso', 'Outros', 'determinadas'],
                'correct_answer' => 2,
                'rationale' => '"Outros" refere-se a indivíduos não especificados no conjunto.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Indica circunstância de lugar em:',
                'options' => ['de 1988 para cá', 'em favor de um sistema', 'no sistema público', 'em todo o país'],
                'correct_answer' => 3,
                'rationale' => '"Em todo o país" é um adjunto adverbial de lugar claro.',
            ],
            [
                'subject' => 'portugues',
                'block' => 8,
                'base_text' => $textSUS,
                'text' => 'Palavra acentuada por ser monossílaba tônica:',
                'options' => ['até', 'às', 'é', 'têm'],
                'correct_answer' => 2,
                'rationale' => '"É" é monossílabo tônico terminado em e.',
            ],

            // --- MATEMÁTICA (21-40) ---
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'O perímetro do retângulo formado por AxB, onde A={0, √5+1} e B={0, √5-1} é aproximadamente:',
                'options' => ['7', '9', '11', '13'],
                'correct_answer' => 1,
                'rationale' => 'Base = √5+1, Altura = √5-1. Perímetro = 2 * (Base + Altura) = 2 * (√5+1 + √5-1) = 2 * (2√5) = 4√5. √5 ≈ 2,23. 4 * 2,23 = 8,92. Aproximadamente 9.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'O valor de √1,777... é:',
                'options' => ['0,333...', '2,333...', '3,333...', '1,333...'],
                'correct_answer' => 3,
                'rationale' => '1,777... = (17 - 1) / 9 = 16/9. √16/9 = 4/3 = 1,333...',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'Para que um canteiro retangular tenha área de 33 m², com medidas (x+√16) e (x-√16), teremos x igual a:',
                'options' => ['10', '8', '7', '6'],
                'correct_answer' => 2,
                'rationale' => '√16 = 4. Área = (x+4)(x-4) = x² - 16. 33 = x² - 16 => x² = 49 => x = 7.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'Um terreno de 50 m² foi loteado nas proporções 1/5, 2/5 e 2/5. A menor área foi de:',
                'options' => ['25m²', '20m²', '15m²', '10m²'],
                'correct_answer' => 3,
                'rationale' => 'Menor parte = 1/5. 1/5 de 50 = 10 m².',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'A forma fatorada (x - 2)(x + 2) resulta em:',
                'options' => ['x² - 4', 'x² - 7x + 4', 'x² - 8x + 4', 'x² + 4'],
                'correct_answer' => 0,
                'rationale' => 'Produto da soma pela diferença: a² - b². x² - 2² = x² - 4.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'A maior raiz da equação x² - 2,333...x + 1,333... = 0 é:',
                'options' => ['1', '4/3', '5/3', '2'],
                'correct_answer' => 1,
                'rationale' => '2,333... = 7/3. 1,333... = 4/3. 3x² - 7x + 4 = 0. Raízes: 1 e 4/3. A maior é 4/3.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'f(3)=7 e f(5)=11 em uma função de 1º grau. O valor de f(10) é:',
                'options' => ['20', '21', '25', '30'],
                'correct_answer' => 1,
                'rationale' => 'Taxa de variação a = (11-7)/(5-3) = 4/2 = 2. f(x) = 2x + b. 7 = 2(3)+b => b=1. f(x)=2x+1. f(10)=2(10)+1 = 21.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'Para cobrir 5x4m com pisos de 25x25cm (caixas com 20), são necessárias:',
                'options' => ['12', '15', '16', '17'],
                'correct_answer' => 2,
                'rationale' => 'Área sala = 20m². Área piso = 0,25*0,25 = 0,0625m². Total pisos = 20 / 0,0625 = 320. Caixas = 320 / 20 = 16.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'A dízima 0,252525... corresponde a:',
                'options' => ['25/9', '25/90', '23/9', '25/99'],
                'correct_answer' => 3,
                'rationale' => 'Período 25 com dois algarismos: 25/99.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'João tem 20 bolinhas (8 a mais que Pedro). Quantas têm juntos?',
                'options' => ['28', '32', '40', '48'],
                'correct_answer' => 1,
                'rationale' => 'João = 20. Pedro = 20 - 8 = 12. Juntos = 20 + 12 = 32.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'Se um círculo de raio r está inscrito em um quadrado de lado 2r, a razão entre a área do círculo e a do quadrado é:',
                'options' => ['π/4', 'π/2', '1/2', 'π/8'],
                'correct_answer' => 0,
                'rationale' => 'Inédita: Área círculo = πr². Área quadrado = (2r)² = 4r². Razão = πr² / 4r² = π/4.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'A fração 3/10.000 corresponde a:',
                'options' => ['0,003', '0,0003', '0,00003', '0,000003'],
                'correct_answer' => 1,
                'rationale' => 'Quatro zeros no denominador = quatro casas decimais.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'O número decimal que corresponde a 1 + 4/100 + 1/1000 é:',
                'options' => ['1,41', '1,401', '1,410', '1,041'],
                'correct_answer' => 3,
                'rationale' => '1 + 0,04 + 0,001 = 1,041.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'Base 5cm e Altura 12cm. A área do triângulo é:',
                'options' => ['16', '12', '24', '30'],
                'correct_answer' => 3,
                'rationale' => 'Área = b*h / 2 = 5 * 12 / 2 = 30 cm².',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'Qual o valor da expressão √(0,444...) + 0,333...?',
                'options' => ['1', '5/3', '1/3', '2/3'],
                'correct_answer' => 0,
                'rationale' => 'Inédita: 0,444... = 4/9. √4/9 = 2/3. 0,333... = 1/3. 2/3 + 1/3 = 3/3 = 1.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => '160 salgados para 5 crianças. Qual a % que cada uma recebeu do total?',
                'options' => ['10%', '15%', '20%', '25%'],
                'correct_answer' => 2,
                'rationale' => 'Cada uma recebeu 1 criança / 5 crianças = 1/5 = 20%.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'Escala 2cm : 7m. Se o desenho tem 10cm, a altura real é:',
                'options' => ['2m', '35m', '50m', '12m'],
                'correct_answer' => 1,
                'rationale' => 'Se 2cm = 7m, então 10cm (5 vezes mais) = 5 * 7m = 35m.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'x(t) = 100 + 8t. Qual instante passa pela posição 260m?',
                'options' => ['10s', '20s', '30s', '40s'],
                'correct_answer' => 1,
                'rationale' => '260 = 100 + 8t => 160 = 8t => t = 20.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'O valor de 4,2% de 600 é:',
                'options' => ['25,2', '33,3', '41,3', '42,3'],
                'correct_answer' => 0,
                'rationale' => '600 * 0,042 = 25,2.',
            ],
            [
                'subject' => 'matematica',
                'block' => 8,
                'text' => 'Anita pagou R$ 57,00 com 5% de desconto. O valor original era:',
                'options' => ['R$ 60,00', 'R$ 57,00', 'R$ 58,00', 'R$ 59,00'],
                'correct_answer' => 0,
                'rationale' => 'Valor * 0,95 = 57. Valor = 57 / 0,95 = 60.',
            ],
        ];

        foreach ($questions as $q) {
            Question::create($q);
        }
    }
}
