<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Question;

class Module09Seeder extends Seeder
{
    public function run(): void
    {
        // Limpar questões antigas do bloco 9 se existirem
        Question::where('block', 9)->delete();

        $textOrelha = "O homem cuja orelha cresceu\n\nEstava escrevendo, sentiu a orelha pesada. Pensou que fosse cansaço, eram 11 da noite, estava fazendo hora extra. Escriturário de uma firma de tecidos, solteiro, 35 anos, ganhava pouco, reforçava com extras. Mas o peso foi aumentando e ele percebeu que as orelhas cresciam. Apavorado, passou a mão. Deviam ter uns dez centímetros. Eram moles, como de cachorro. Correu ao banheiro. Ficou só olhando. Elas cresciam, chegavam à cintura. Finas, compridas, como fitas de carne, enrugadas. Procurou uma tesoura, ia cortar a orelha, não importava que doesse. Mas não encontrou, as gavetas das moças estavam fechadas. O armário de material também. O melhor era correr para a pensão, se fechar, antes que não pudesse mais andar na rua. Se tivesse um amigo, ou namorada, iria mostrar o que estava acontecendo. Mas o escriturário não conhecia ninguém a não ser os colegas de escritório. Colegas, não amigos. Ele abriu a camisa, enfiou as orelhas para dentro. Enrolou uma toalha na cabeça, como se estivesse machucado.\n\nQuando chegou na pensão, a orelha saía pela perna da calça. O escriturário tirou a roupa. Deitou-se, louco para dormir e esquecer. E se fosse ao médico? Um otorrinolaringologista. A esta hora da noite? Olhava o forro branco. Incapaz de pensar, dormiu de desespero.\n\nAo acordar, viu aos pés da cama o monte de uns trinta centímetros de altura. A orelha crescera e se enrolara como cobra. Tentou se levantar. Difícil. Precisava segurar as orelhas enroladas. Pesavam. Ficou na cama. E sentia a orelha crescendo, com uma cosquinha. O sangue correndo para lá, os nervos, músculos, a pele se formando, rápido. Às quatro da tarde, toda a cama tinha sido tomada pela orelha. O escriturário sentia fome, sede. Às dez da noite, sua barriga roncava. A orelha tinha caído para fora da cama. Dormiu.\n\nAcordou no meio da noite com o barulhinho da orelha crescendo. Dormiu de novo e quando acordou na manhã seguinte, o quarto se enchera com a orelha. Ela estava em cima do guarda-roupa, embaixo da cama, na pia. E forçava a porta. Ao meio-dia, a orelha derrubou a porta, saiu pelo corredor. Duas horas mais tarde, encheu o corredor. Inundou a casa. Os hóspedes fugiram para a rua. Chamaram a polícia, o corpo de bombeiros. A orelha saiu para o quintal. Para a rua.\n\nVieram os açougueiros com facas, machados, serrotes. Os açougueiros trabalharam o dia inteiro cortando e amontoando. O prefeito mandou dar a carne aos pobres. Vieram os favelados, as organizações de assistência social, irmandades religiosas, donos de restaurantes, vendedores de churrasquinho na porta do estádio, donas de casa. Vinham com cestas, carrinhos, carroças, camionetes. Toda a população apanhou carne de orelha. Apareceu um administrador, trouxe sacos de plástico, higiênicos, organizou filas, fez uma distribuição racional.\n\nE, quando todos tinham levado carne para aquele dia e para os outros, começaram a estocar. Encheram silos, frigoríficos, geladeiras. Quando não havia mais onde estocar a carne de orelha, chamaram outras cidades. Vieram novos açougueiros. E a orelha crescia, era cortada e crescia, e os açougueiros trabalhavam Toda a população apanhou carne de orelha. E a cidade não suportava mais carne de orelha. O povo pediu uma providência ao prefeito. E o prefeito ao governador. E o governador ao presidente. E quando não havia solução, um menino, diante da rua cheia de carne de orelha, disse a um policial: “Por que o senhor não mata o dono da orelha”?\n\n(Ignácio de Loyola Brandão)";

        $questions = [
            // PORTUGUÊS (1-20)
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'O texto:',
                'options' => ['comenta um fato comum na nossa vida cotidiana.', 'analisa em minúcias um fato que se aproxima da realidade.', 'relata uma história que não tem relação alguma com a realidade.', 'descreve um personagem que se transforma gradativamente.'],
                'correct_answer' => 3,
                'rationale' => 'Trata-se de um conto fantástico onde um homem comum passa por uma transformação física absurda e gradual (o crescimento infinito da orelha).',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => '“Às quatro da tarde, toda a cama tinha sido tomada pela orelha.” A vírgula foi utilizada nesse trecho para:',
                'options' => ['Isolar um termo vocativo.', 'Separar itens de uma sequência.', 'Isolar um adjunto adverbial com valor de tempo.', 'Representar um verbo implícito.'],
                'correct_answer' => 2,
                'rationale' => '“Às quatro da tarde” indica tempo e está deslocado para o início da frase, exigindo/permitindo o uso da vírgula.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Acerca da vida social do personagem principal, pode-se dizer que:',
                'options' => ['Ele tinha um grande círculo de amizades.', 'Ele tinha muitos colegas de trabalho e raros amigos.', 'Ele era uma pessoa depressiva e com tendência suicida.', 'Ele era uma pessoa solitária, com alguns colegas.'],
                'correct_answer' => 3,
                'rationale' => 'O texto afirma que ele não conhecia ninguém a não ser os colegas, e enfatiza: "Colegas, não amigos", indicando solidão.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => '“A orelha crescera e se enrolara como cobra. Tentou se levantar.” O sujeito do verbo sublinhado (Tentou) é:',
                'options' => ['A orelha.', 'Cobra.', 'Oculto.', 'Indeterminado.'],
                'correct_answer' => 2,
                'rationale' => 'O sujeito é "O homem" ou "O escriturário", que não aparece explicitamente na oração mas é deduzido pelo contexto.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => '“E a orelha crescia, era cortada e crescia...”. Os verbos destacados (crescia, trabalhavam, suportava) foram conjugados:',
                'options' => ['No presente do modo indicativo.', 'No pretérito perfeito do modo subjuntivo.', 'No pretérito imperfeito do modo subjuntivo.', 'No pretérito imperfeito do modo indicativo.'],
                'correct_answer' => 3,
                'rationale' => 'A terminação -ia e -avam indica ações habituais ou duradouras no passado (Pretérito Imperfeito do Indicativo).',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Quanto à sugestão apresentada pelo menino no desfecho da narrativa, trata-se de:',
                'options' => ['uma medida normal.', 'uma providência tolerável.', 'uma atitude extrema.', 'um procedimento banal.'],
                'correct_answer' => 2,
                'rationale' => 'A sugestão de "matar o dono" para resolver o problema da carne é uma solução drástica e violenta (atitude extrema).',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale a opção em que NÃO há parentesco semântico entre a palavra sublinhada e a outra ao lado:',
                'options' => ['escriturário / escritório', 'pensão / pensar', 'gavetas / engavetar', 'solução / solucionar'],
                'correct_answer' => 1,
                'rationale' => '"Pensão" (local de moradia) e "Pensar" (ato cognitivo) não possuem a mesma raiz etimológica ou relação de sentido direto.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Em todas as opções o termo sublinhado é um adjetivo, EXCETO em:',
                'options' => ['orelha pesada', 'novos açougueiros', 'otorrinolaringologista', 'moles'],
                'correct_answer' => 2,
                'rationale' => '"Otorrinolaringologista" é um substantivo que designa uma profissão/especialidade médica.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale a opção que contém uma forma verbal no pretérito mais-que-perfeito:',
                'options' => ['ganhava pouco', 'tirou a roupa', 'viu aos pés da cama', 'o quarto se enchera'],
                'correct_answer' => 3,
                'rationale' => '"Enchera" é o pretérito mais-que-perfeito simples do verbo encher.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => '“Ficou só olhando.” A palavra sublinhada NÃO pode ser substituída por:',
                'options' => ['apenas.', 'unicamente.', 'sozinho.', 'somente.'],
                'correct_answer' => 2,
                'rationale' => 'No contexto, "só" significa "apenas". "Sozinho" mudaria o sentido para isolamento físico, não exclusividade da ação.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale a opção em que as duas palavras sublinhadas são adjetivos:',
                'options' => ['Apavorado / moles', 'sangue / rápido', 'trabalharam / amontoando', 'tirou / louco'],
                'correct_answer' => 0,
                'rationale' => 'Apavorado (estado do homem) e Moles (característica das orelhas) são adjetivos.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale a opção em que a palavra destacados é uma oxítona:',
                'options' => ['Difícil', 'pés', 'ninguém', 'só'],
                'correct_answer' => 2,
                'rationale' => '"Ninguém" é oxítona terminada em -em. "Só" e "pés" são monossílabos tônicos.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => '“Quando chegou na pensão...”. Substituição correta para a expressão sublinhada:',
                'options' => ['Contanto que', 'Ao passo que', 'Assim que', 'Não obstante'],
                'correct_answer' => 2,
                'rationale' => '"Assim que" mantém a ideia de tempo/conjunção temporal idêntica ao "Quando".',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => '“A orelha crescera...”. A forma verbal sublinhada está corretamente substituída por:',
                'options' => ['crescia', 'havia crescido', 'estava crescendo', 'podia crescer'],
                'correct_answer' => 1,
                'rationale' => 'O pretérito mais-que-perfeito simples (crescera) equivale ao composto (havia crescido).',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale o trecho que apresenta uma circunstância de lugar:',
                'options' => ['na manhã seguinte', 'aos pés da cama', 'o dia inteiro', 'não suportava mais'],
                'correct_answer' => 1,
                'rationale' => '"Aos pés da cama" indica a localização onde ele viu o monte.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale a opção em que a forma verbal está na voz passiva:',
                'options' => ['estava acontecendo', 'tinham levado', 'tinha caído', 'era cortada'],
                'correct_answer' => 3,
                'rationale' => '"Era cortada" (verbo ser + particípio) indica que a orelha sofria a ação de ser cortada.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale a opção em que a expressão sublinhada é um objeto direto:',
                'options' => ['apanhou carne de orelha', 'se enrolara como cobra', 'cidade não suportava', 'Vieram os favelados'],
                'correct_answer' => 0,
                'rationale' => 'Quem apanha, apanha algo. "Carne de orelha" completa o sentido sem preposição obrigatória.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale a opção em que a expressão sublinhada é o SUJEITO da oração:',
                'options' => ['um menino', 'a orelha crescia', 'iria mostrar', 'não conhecia ninguém'],
                'correct_answer' => 1,
                'rationale' => '"A orelha" é quem realizava a ação de crescer.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale a alternativa que NÃO apresenta circunstância de tempo:',
                'options' => ['Às quatro da tarde', 'no meio da noite', 'na manhã seguinte', 'cheia de carne de orelha'],
                'correct_answer' => 3,
                'rationale' => '"Cheia de carne de orelha" é uma característica/estado da rua, não tempo.',
            ],
            [
                'subject' => 'portugues',
                'block' => 9,
                'base_text' => $textOrelha,
                'text' => 'Assinale a alternativa em que a palavra destacados é um pronome de tratamento:',
                'options' => ['o senhor', 'ninguém', 'todos', 'outros'],
                'correct_answer' => 0,
                'rationale' => '"Senhor" é um pronome de tratamento usado para respeito.',
            ],

            // MATEMÁTICA (21-40)
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'O valor da expressão (√0,25 * 2,4 * 0,7) / (1 - 0,888...) é igual a:',
                'options' => ['6,8', '7,5', '8,75', '9,25'],
                'correct_answer' => 1,
                'rationale' => '√0,25 = 0,5. Numerador = 0,5 * 2,4 * 0,7 = 1,2 * 0,7 = 0,84. Denominador = 1 - 8/9 = 1/9. 0,84 / (1/9) = 0,84 * 9 = 7,56. Gabarito B (7,5).',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'Se a² = 2³ e b³ = 2², então (a * b)⁶ é igual a:',
                'options' => ['2⁶', '2¹⁰', '2¹²', '2¹³'],
                'correct_answer' => 3,
                'rationale' => 'a = 2^(3/2), b = 2^(2/3). (a*b)⁶ = a⁶ * b⁶ = (2^(3/2))⁶ * (2^(2/3))⁶ = 2⁹ * 2⁴ = 2¹³.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'Quais as soluções reais da equação x² - 15X + 56 = 0?',
                'options' => ['(9,6)', '(-9,6)', '(8,7)', '(14,4)'],
                'correct_answer' => 2,
                'rationale' => 'Soma = 15, Produto = 56. 8 * 7 = 56, 8 + 7 = 15. Raízes: 8 e 7.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'O número que deve ser adicionado a -33, para se obter +16, é igual a:',
                'options' => ['+49', '-17', '+17', '-16'],
                'correct_answer' => 0,
                'rationale' => '-33 + x = 16 => x = 16 + 33 = 49.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'O valor de 256^(-1/2) é igual ao valor de:',
                'options' => ['16⁻¹', '(1/2)⁶', '2⁻²', '4²'],
                'correct_answer' => 0,
                'rationale' => '256^(-1/2) = 1 / √256 = 1 / 16 = 16⁻¹.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'Calculando √(2/11) * √(2 - 1/3 + 1/4 - 1/12), obtemos:',
                'options' => ['√(12/2)', '1', '√6/2', '√(2/6)'],
                'correct_answer' => 3,
                'rationale' => '2 - 1/3 + 1/4 - 1/12 = (24-4+3-1)/12 = 22/12 = 11/6. √(2/11) * √(11/6) = √(2/6).',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'Se A = 64^(1/3) + 81^(1/4) - (-2)² + 125^(2/3), então A vale:',
                'options' => ['20', '28', '36', '24'],
                'correct_answer' => 1,
                'rationale' => 'A = 4 + 3 - 4 + 25 = 28.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'O radical equivalente a ∛4 * √5 é:',
                'options' => ['⁶√2000', '⁶√7200', '⁶√3600', '⁶√6000'],
                'correct_answer' => 0,
                'rationale' => '⁴^(1/3) * 5^(1/2) = 4^(2/6) * 5^(3/6) = ⁶√(4² * 5³) = ⁶√(16 * 125) = ⁶√2000.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'Qual a fração geratriz da dízima periódica 3,1818...?',
                'options' => ['315/99', '18/99', '318/99', '318/90'],
                'correct_answer' => 0,
                'rationale' => '(318 - 3) / 99 = 315/99.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'A raiz da equação 8^x = 262.144 é igual a:',
                'options' => ['4', '5', '6', '7'],
                'correct_answer' => 2,
                'rationale' => '8¹=8, 8²=64, 8³=512, 8⁴=4096, 8⁵=32768, 8⁶=262144.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'Para x = -2, o valor de √(3x² + 2x + 1) é igual a:',
                'options' => ['-2', '3', '1', '2'],
                'correct_answer' => 1,
                'rationale' => '√(3(-2)² + 2(-2) + 1) = √(12 - 4 + 1) = √9 = 3.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'A soma e o produto das raízes da equação (x+3)(x+1) = -(4x+12) são:',
                'options' => ['-8 e 15', '-5 e 14', '5 e -14', '-5 e -14'],
                'correct_answer' => 0,
                'rationale' => 'x² + 4x + 3 = -4x - 12 => x² + 8x + 15 = 0. Soma = -8, Produto = 15.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'A figura mostra um retângulo com área de 242 cm² e o maior lado é o dobro do menor. Qual equação define o lado menor y?',
                'options' => ['y² – 242 = 0', 'y² – 121 = 0', 'y² + 242 = 0', 'y² + 121 = 0'],
                'correct_answer' => 1,
                'image_url' => '/questions/block9_q33.png',
                'rationale' => 'Lados y e 2y. Área = 2y² = 242 => y² = 121 => y² - 121 = 0.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'As raízes da equação x² – 5x + 6 = 0, são:',
                'options' => ['2 ou -3', '-2 ou 3', '2 ou 3', '-2 ou -3'],
                'correct_answer' => 2,
                'rationale' => 'Soma 5, Produto 6. Raízes: 2 e 3.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'Um retângulo tem 54 cm² de área, comprimento (x - 1) e largura (x - 4). O valor de x é:',
                'options' => ['-5', '9', '10', '54'],
                'correct_answer' => 2,
                'rationale' => '(x-1)(x-4) = 54 => x² - 5x + 4 = 54 => x² - 5x - 50 = 0. Raízes: 10 e -5. Medida positiva: 10.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'Francisca e João repartirão um bolo de 1200g na razão de 3/2. Qual a parte de cada um?',
                'options' => ['F: 1080g / J: 120g', 'F: 400g / J: 600g', 'F: 600g / J: 600g', 'F: 720g / J: 480g'],
                'correct_answer' => 3,
                'rationale' => 'Total parts: 3+2=5. Unit: 1200/5 = 240. F: 3*240=720. J: 2*240=480.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'image_url' => '/questions/block9_q37.png',
                'text' => 'A tabela de sacos de ração vs galinhas segue uma proporção direta. Quais valores completam a tabela?',
                'options' => ['9 e 11', '12 e 14', '9 e 9', '10 e 12'],
                'correct_answer' => 0,
                'rationale' => 'Ratio x:y = 2:6 (1:3). For x=3, y=9. For y=33, x=11.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'image_url' => '/questions/block9_q38.png',
                'text' => 'Paulo ia ao trabalho, o pneu furou e ele continuou após trocar. Qual gráfico representa a distância de casa vs tempo?',
                'options' => ['(a)', '(b)', '(c)', '(d)'],
                'correct_answer' => 2,
                'rationale' => 'O gráfico (c) mostra um aumento (indo), parado (horizontal - trocando pneu) e novo aumento (continuando).',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'image_url' => '/questions/block9_q39.png',
                'text' => 'Os lados do retângulo medem (x-3) e (3x+1). O polinômio da área é:',
                'options' => ['2x² + 13x + 15', '3x² - 8x - 3', '2x² + 8', '3x² + 8x + 8'],
                'correct_answer' => 1,
                'rationale' => '(x-3)(3x+1) = 3x² + x - 9x - 3 = 3x² - 8x - 3.',
            ],
            [
                'subject' => 'matematica',
                'block' => 9,
                'text' => 'O valor de 30² - 50² é igual a:',
                'options' => ['-900', '90', '900', '-1600'],
                'correct_answer' => 3,
                'rationale' => '900 - 2500 = -1600.',
            ],
        ];

        foreach ($questions as $q) {
            Question::create($q);
        }
    }
}
